### ISSUE TITLE
Error message inconsistent with ORS error messages

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openpoiservice#15]
One more:
when HTTP error occurs, the message body is `{'message':..}`, while for most ORS errors it seems to be `{'error': {'message':...}}`. Would make sense to provide the same format. Very minor issue. But in ors-py, it's handled in ORS format.

**Comment by TheGreatRefrigerator** [comment]
Example from /directions: 
https://api.openrouteservice.org/directions?api_key=xxx&attributes=detouractor|percentage&coordinates=8.324397,48.790439|8.342121,48.786523&elevation=true&extra_info=steepness|waytype|surface&geometry=true&geometry_format=geojson&instructions=true&instructions_format=html&preference=fastest&profile=driving-ca&units=m

`{"error":{"code":2003,"message":"Unknown parameter value 'driving-ca' for 'profile'."},"info":{"engine":{"version":"4.5.0","build_date":"2018-03-26T14:15:39Z"},"timestamp":1524574404263}}`
