### ISSUE TITLE
Is it possible to use an external database?

### ISSUE THREAD

**Issue by kshnkvn** [GIScience/openpoiservice#72]
Can someone please explain the mechanism of working with OSM files? I understand correctly that after importing the OSM file is no longer used and can it be deleted? Those. all data for work is taken only from the database, or not? If so, can I run the database on a separate server and connect to it?

**Comment by TimMcCauley** [comment]
Hi @kshnkvn, 

> Can someone please explain the mechanism of working with OSM files? I understand correctly that after importing the OSM file is no longer used and can it be deleted? 

Yes 

> Those. all data for work is taken only from the database, or not? If so, can I run the database on a separate server and connect to it?

Yes & yes (you can configure this in the config file)
